version: '3.3'

services:
  prusa-camera:
    image: linuxserver/ffmpeg
    restart: always
    entrypoint: /bin/bash
    command: /upload.sh
    environment:
      RTSP_URL: ${RTSP_URL}
      FINGERPRINT: ${FINGERPRINT}
      TOKEN: ${TOKEN}
    volumes:
      - ./upload.sh:/upload.sh